/// Integration tests for backend-cpp.
///
/// The backend emits 5 files:
///   files[0] = CMakeLists.txt
///   files[1] = include/<module>.hpp
///   files[2] = include/nanocbor_compat.h
///   files[3] = src/<module>.cpp
///   files[4] = test/test_roundtrip.cpp

use std::path::PathBuf;
use backend_cpp::CppBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

// ── Helpers ───────────────────────────────────────────────────────────────────

struct GeneratedCrate {
    cmake:  String,
    header: String,
    source: String,
    tests:  String,
}

fn compile(src: &str) -> GeneratedCrate {
    compile_with_opts(src, CodegenOptions::default())
}

fn compile_with_opts(src: &str, opts: CodegenOptions) -> GeneratedCrate {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let out     = CppBackend.generate(&lowered.module, &opts).expect("generate");
    assert_eq!(out.files.len(), 5, "expected 5 output files");
    GeneratedCrate {
        cmake:  out.files[0].content.clone(),
        header: out.files[1].content.clone(),
        // files[2] = include/nanocbor_compat.h (platform shim, not tested here)
        source: out.files[3].content.clone(),
        tests:  out.files[4].content.clone(),
    }
}

// ── Crate structure ───────────────────────────────────────────────────────────

#[test]
fn test_emits_four_files() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = CppBackend.generate(&lowered.module, &opts).unwrap();
    assert_eq!(out.files.len(), 5);
    assert!(out.files[0].path.ends_with("CMakeLists.txt"));
    assert!(out.files[1].path.ends_with(".hpp"));
    assert!(out.files[2].path.ends_with("nanocbor_compat.h"));
    assert!(out.files[3].path.ends_with(".cpp"));
    assert!(out.files[4].path.ends_with("test_roundtrip.cpp"));
}

#[test]
fn test_crate_dir_named_after_module() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("sensor.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = CppBackend.generate(&lowered.module, &opts).unwrap();
    assert!(out.files[0].path.starts_with("sensor-cbor-cpp/"));
    assert!(out.files[1].path.starts_with("sensor-cbor-cpp/include/"));
    assert!(out.files[2].path.starts_with("sensor-cbor-cpp/include/"));
    assert!(out.files[3].path.starts_with("sensor-cbor-cpp/src/"));
    assert!(out.files[4].path.starts_with("sensor-cbor-cpp/test/"));
}

// ── CMakeLists.txt ────────────────────────────────────────────────────────────

#[test]
fn test_cmake_generated_comment() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("@generated by cddlc"));
}

#[test]
fn test_cmake_cpp17_standard() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("CMAKE_CXX_STANDARD 17"));
}

#[test]
fn test_cmake_nanocbor() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("nanocbor") || g.cmake.contains("NanoCBOR"));
}

// ── Header file ───────────────────────────────────────────────────────────────

#[test]
fn test_header_generated_comment() {
    let g = compile("x = uint");
    assert!(g.header.contains("@generated by cddlc"));
}

#[test]
fn test_header_include_guard() {
    let g = compile("x = uint");
    assert!(g.header.contains("#ifndef") && g.header.contains("_HPP"));
}

#[test]
fn test_header_cpp_includes() {
    let g = compile("x = uint");
    assert!(g.header.contains("#include <optional>"));
    assert!(g.header.contains("#include <variant>"));
    assert!(g.header.contains("#include <string_view>"));
}

#[test]
fn test_header_namespace() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("namespace "));
    assert!(g.header.contains("} // namespace") || g.header.contains("}}"));
}

#[test]
fn test_header_error_code_enum_class() {
    let g = compile("x = uint");
    assert!(g.header.contains("enum class ErrorCode"));
    assert!(g.header.contains("TagMismatch"));
    assert!(g.header.contains("ValidationFailed"));
}

#[test]
fn test_header_field_error_struct() {
    let g = compile("x = uint");
    assert!(g.header.contains("struct FieldError"));
    assert!(g.header.contains("ErrorCode"));
}

#[test]
fn test_header_callbacks_struct() {
    let g = compile("x = uint");
    assert!(g.header.contains("struct Callbacks"));
    assert!(g.header.contains("on_error"));
    assert!(g.header.contains("on_unknown_field"));
}

// ── Struct declaration ────────────────────────────────────────────────────────

#[test]
fn test_struct_decl() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.header.contains("struct Sensor {"));
}

#[test]
fn test_struct_uint_field() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("uint64_t id"));
}

#[test]
fn test_struct_float_field() {
    let g = compile("sensor = { value: float32 }");
    assert!(g.header.contains("float value"));
}

#[test]
fn test_struct_tstr_field_is_string_view() {
    let g = compile("msg = { label: tstr }");
    assert!(g.header.contains("std::string_view label"));
}

#[test]
fn test_optional_field_is_std_optional() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    assert!(g.header.contains("std::optional<"));
}

#[test]
fn test_struct_equality_operator() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("operator=="));
}

// ── Enum declaration ──────────────────────────────────────────────────────────

#[test]
fn test_enum_uses_std_variant() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.header.contains("std::variant"));
}

#[test]
fn test_enum_named_constructors() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.header.contains("make_Ok") || g.header.contains("make_"));
}

#[test]
fn test_enum_equality_operator() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.header.contains("operator=="));
}

// ── Array declaration ─────────────────────────────────────────────────────────

#[test]
fn test_array_uses_std_array() {
    let g = compile("; @capacity 8\nreadings = [* float32]");
    assert!(g.header.contains("std::array<"));
}

#[test]
fn test_array_has_count_field() {
    let g = compile("; @capacity 8\nreadings = [* float32]");
    assert!(g.header.contains("count{0}") || g.header.contains("count;"));
}

// ── Alias declaration ─────────────────────────────────────────────────────────

#[test]
fn test_simple_alias_using() {
    let g = compile("device-id = uint");
    assert!(g.header.contains("using DeviceId =") || g.header.contains("DeviceId"));
}

#[test]
fn test_constrained_alias_struct() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.header.contains("struct DeviceId"));
}

// ── Tagged types ──────────────────────────────────────────────────────────────

#[test]
fn test_tagged_encode_emits_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("nanocbor_fmt_tag") && g.source.contains("1"));
}

#[test]
fn test_tagged_decode_verifies_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("nanocbor_get_tag"));
    assert!(g.source.contains("return -1"));
}

// ── Forward declarations ──────────────────────────────────────────────────────

#[test]
fn test_forward_declarations() {
    let g = compile("a = { x: uint }\nb = { y: float32 }");
    assert!(g.header.contains("struct A;") || g.header.contains("Forward"));
}

// ── Source file ───────────────────────────────────────────────────────────────

#[test]
fn test_source_generated_comment() {
    let g = compile("x = uint");
    assert!(g.source.contains("@generated by cddlc"));
}

#[test]
fn test_source_includes_header() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("#include") && g.source.contains(".hpp\""));
}

#[test]
fn test_source_in_namespace() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("namespace "));
}

#[test]
fn test_struct_encode_maps_fields() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.source.contains("nanocbor_fmt_map"));
}

#[test]
fn test_struct_decode_enters_map() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("nanocbor_enter_map"));
}

#[test]
fn test_unknown_field_handled() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("on_unknown_field"));
    assert!(g.source.contains("nanocbor_skip"));
}

#[test]
fn test_enum_encode_uses_std_visit() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("std::visit"));
}

#[test]
fn test_dcbor_sorts_keys() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    let a_pos = g.source.find("\"a\"").unwrap_or(usize::MAX);
    let b_pos = g.source.find("\"b\"").unwrap_or(0);
    assert!(a_pos < b_pos, "dCBOR: 'a' should be encoded before 'b'");
}

// ── Test file ─────────────────────────────────────────────────────────────────

#[test]
fn test_roundtrip_generated_comment() {
    let g = compile("x = uint");
    assert!(g.tests.contains("@generated by cddlc"));
}

#[test]
fn test_roundtrip_uses_namespace() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("using namespace"));
}

#[test]
fn test_roundtrip_has_test_functions() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("test_") && g.tests.contains("_roundtrip"));
}

#[test]
fn test_roundtrip_encode_decode_cycle() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("nanocbor_encoder_init"));
    assert!(g.tests.contains("nanocbor_decoder_init"));
    assert!(g.tests.contains("encode("));
    assert!(g.tests.contains("decode("));
}

#[test]
fn test_roundtrip_equality_assert() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("original == decoded") || g.tests.contains("assert("));
}

#[test]
fn test_roundtrip_has_main() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("int main("));
}

#[test]
fn test_iot_schema() {
    let g = compile(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: #6.1(uint),
}
device-id = tstr .size 16
"#);
    assert!(g.header.contains("SensorMessage") || g.header.contains("sensor_message"));
    assert!(g.header.contains("DeviceId") || g.header.contains("device_id"));
}
