/// C++ backend for cddlc.
///
/// Emits a C++17 library crate wrapping the C nanocbor runtime:
///   <module>-cbor/
///     CMakeLists.txt
///     include/<module>.hpp    ← types in namespace, std::optional, std::variant
///     src/<module>.cpp        ← encode/decode implementations
///     test/test_roundtrip.cpp ← roundtrip tests

use cddlc_codegen::{
    capacity_value, constraint_to_cpp_check,
    to_pascal_case, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Capacity, Constraint, EnumDef,
    IrModule, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct CppBackend;

impl Backend for CppBackend {
    fn language_name(&self) -> &str { "C++" }
    fn file_extension(&self) -> &str { "hpp" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name      = module.name.as_str();
        let fmt_tag   = if opts.is_json() { "json" } else { "cbor" };
        let crate_dir = format!("{name}-{fmt_tag}-cpp");

        if opts.is_json() {
            return Ok(CodegenOutput {
                files: vec![
                    GeneratedFile {
                        path:    format!("{crate_dir}/CMakeLists.txt"),
                        content: emit_cmake_json_cpp(name, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/include/{name}.hpp"),
                        content: emit_header_json_cpp(module, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/src/{name}.cpp"),
                        content: emit_source_json_cpp(module, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/test/test_roundtrip.cpp"),
                        content: emit_tests_json_cpp(module, opts),
                    },
                ],
            });
        }

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{crate_dir}/CMakeLists.txt"),
                    content: emit_cmake(name, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/{name}.hpp"),
                    content: emit_header(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/nanocbor_compat.h"),
                    content: NANOCBOR_MACOS_COMPAT_H.to_string(),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/src/{name}.cpp"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/test/test_roundtrip.cpp"),
                    content: emit_tests(module, opts),
                },
            ],
        })
    }
}

// ── macOS compat header ───────────────────────────────────────────────────────

/// Compatibility shim for nanocbor on macOS — see backend-c for details.
const NANOCBOR_MACOS_COMPAT_H: &str = r#"/* @generated by cddlc — do not edit manually */
/* macOS compatibility shim for nanocbor byte-order functions */
#pragma once
#include <libkern/OSByteOrder.h>
/* Override nanocbor/config.h default so it does not request Linux endian.h */
#define NANOCBOR_BYTEORDER_HEADER <libkern/OSByteOrder.h>
/* Map Linux byte-order functions to their macOS equivalents */
#define be16toh(x) OSSwapBigToHostInt16(x)
#define be32toh(x) OSSwapBigToHostInt32(x)
#define be64toh(x) OSSwapBigToHostInt64(x)
#define htobe16(x) OSSwapHostToBigInt16(x)
#define htobe32(x) OSSwapHostToBigInt32(x)
#define htobe64(x) OSSwapHostToBigInt64(x)
#define le16toh(x) OSSwapLittleToHostInt16(x)
#define le32toh(x) OSSwapLittleToHostInt32(x)
#define le64toh(x) OSSwapLittleToHostInt64(x)
#define htole16(x) OSSwapHostToLittleInt16(x)
#define htole32(x) OSSwapHostToLittleInt32(x)
#define htole64(x) OSSwapHostToLittleInt64(x)
"#;

// ── CMakeLists.txt ────────────────────────────────────────────────────────────

fn emit_cmake(name: &str, _opts: &CodegenOptions) -> String {
    format!(r#"# @generated by cddlc — do not edit manually
cmake_minimum_required(VERSION 3.17)
project({name}_cbor_cpp C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# macOS: force-include compat shim for nanocbor's Linux byte-order functions.
# Must be set before FetchContent_MakeAvailable so it applies to nanocbor's
# own compilation units as well.
if(APPLE)
    set(_nanocbor_compat "${{CMAKE_CURRENT_SOURCE_DIR}}/include/nanocbor_compat.h")
    add_compile_options(-include "${{_nanocbor_compat}}")
endif()

include(FetchContent)
FetchContent_Declare(nanocbor
    GIT_REPOSITORY https://github.com/bergzand/NanoCBOR.git
    GIT_TAG        master
)
set(NANOCBOR_BUILD_TESTS OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(nanocbor)

file(GLOB NANOCBOR_SOURCES "${{nanocbor_SOURCE_DIR}}/src/*.c")

add_library({name}_cbor_cpp
    src/{name}.cpp
    ${{NANOCBOR_SOURCES}}
)
target_include_directories({name}_cbor_cpp PUBLIC include ${{nanocbor_SOURCE_DIR}}/include)

enable_testing()
add_executable(test_roundtrip test/test_roundtrip.cpp)
target_link_libraries(test_roundtrip {name}_cbor_cpp)
add_test(NAME roundtrip COMMAND test_roundtrip)
"#)
}

// ── Header file ───────────────────────────────────────────────────────────────

fn emit_header(module: &IrModule, opts: &CodegenOptions) -> String {
    let name    = module.name.as_str();
    let guard   = format!("{}_HPP", name.to_uppercase().replace('-', "_"));
    let ns      = to_snake_case(name);
    let mut w   = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line(&format!("#ifndef {guard}"));
    w.line(&format!("#define {guard}"));
    w.blank();
    w.line("#include <cstdint>");
    w.line("#include <cstddef>");
    w.line("#include <optional>");
    w.line("#include <variant>");
    w.line("#include <string_view>");
    w.line("#include <array>");
    w.line("#include <cstring>");
    w.line("#include <nanocbor/nanocbor.h>");
    w.blank();

    w.line(&format!("namespace {ns} {{"));
    w.blank();

    // ── Error codes ───────────────────────────────────────────────────────────
    w.line("enum class ErrorCode {");
    w.indent();
    w.line("Ok = 0,");
    w.line("UnexpectedType,");
    w.line("UnexpectedValue,");
    w.line("MissingField,");
    w.line("Overflow,");
    w.line("InvalidUtf8,");
    w.line("UnknownField,");
    w.line("TagMismatch,");
    w.line("ValidationFailed,");
    w.dedent();
    w.line("};");
    w.blank();

    w.line("struct FieldError {");
    w.indent();
    w.line("ErrorCode   code;");
    w.line("const char *field;");
    w.line("std::size_t index{0};");
    w.dedent();
    w.line("};");
    w.blank();

    // ── Callbacks ─────────────────────────────────────────────────────────────
    w.line("struct Callbacks {");
    w.indent();
    w.line("void (*on_error)(void *ctx, FieldError err){nullptr};");
    w.line("void (*on_unknown_field)(void *ctx, std::string_view key){nullptr};");
    w.dedent();
    w.line("};");
    w.blank();

    // ── Forward declarations ──────────────────────────────────────────────────
    w.line("// Forward declarations");
    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(_) | TypeDef::Enum(_) => {
                w.line(&format!("struct {};", to_pascal_case(def.name())));
            }
            _ => {}
        }
    }
    w.blank();

    // ── Type declarations ─────────────────────────────────────────────────────
    for (_, def) in &module.types {
        emit_type_decl_hpp(&mut w, def, opts);
        w.blank();
    }

    // ── Function declarations ─────────────────────────────────────────────────
    w.line("// Encode/decode function declarations");
    for (_, def) in &module.types {
        let type_name = to_pascal_case(def.name());
        w.line(&format!(
            "int encode(nanocbor_encoder_t *enc, const {type_name} &val);"
        ));
        w.line(&format!(
            "int decode(nanocbor_value_t *dec, {type_name} &out, const Callbacks &cb = {{}}, void *ctx = nullptr);"
        ));
    }
    w.blank();

    w.line(&format!("}} // namespace {ns}"));
    w.blank();
    w.line(&format!("#endif // {guard}"));
    w.finish()
}

fn emit_type_decl_hpp(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_hpp(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_hpp(w, e, opts),
        TypeDef::Array(a)  => emit_array_hpp(w, a, opts),
        TypeDef::Alias(a)  => emit_alias_hpp(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

fn emit_struct_hpp(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    if let Some(d) = s.doc.as_deref() {
        w.line(&format!("/// {d}"));
    }
    let type_name = to_pascal_case(&s.name);
    w.line(&format!("struct {type_name} {{"));
    w.indent();
    for f in &s.fields {
        if let Some(d) = f.doc.as_deref() {
            w.line(&format!("/// {d}"));
        }
        let ty_str = cpp_field_type(&f.ty, &f.occurrence, opts);
        let fname  = to_snake_case(&f.name);
        w.line(&format!("{ty_str} {fname}{{}};"));
    }
    w.blank();
    w.line(&format!("bool operator==(const {type_name} &o) const noexcept {{"));
    w.indent();
    if s.fields.is_empty() {
        w.line("return true;");
    } else {
        let eq = s.fields.iter()
            .map(|f| format!("{} == o.{}", to_snake_case(&f.name), to_snake_case(&f.name)))
            .collect::<Vec<_>>()
            .join(" && ");
        w.line(&format!("return {eq};"));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("};");
}

fn emit_enum_hpp(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    if let Some(d) = e.doc.as_deref() {
        w.line(&format!("/// {d}"));
    }
    let type_name = to_pascal_case(&e.name);

    // Build std::variant type list
    let variant_types: Vec<String> = e.variants.iter()
        .map(|v| match &v.ty {
            TypeRef::Primitive(Primitive::Null) => "std::monostate".into(),
            TypeRef::Primitive(p)  => cpp_primitive(p, opts).to_owned(),
            TypeRef::Named(n)      => to_pascal_case(n),
            _                      => "std::monostate".into(),
        })
        .collect();

    // Deduplicate while preserving order
    let mut seen = std::collections::HashSet::new();
    let unique_types: Vec<&str> = variant_types.iter()
        .filter(|t| seen.insert(t.as_str()))
        .map(|s| s.as_str())
        .collect();

    w.line(&format!("struct {type_name} {{"));
    w.indent();
    w.line(&format!("using Variant = std::variant<{}>;", unique_types.join(", ")));
    // Default-initialize to the first variant's value so default-constructed
    // instances are valid for encode/decode roundtrip tests.
    let default_init = e.variants.first().map(|v| match &v.ty {
        TypeRef::Primitive(Primitive::Null) => "std::monostate{}".into(),
        TypeRef::Primitive(Primitive::Tstr) => {
            let s = v.name.to_lowercase().replace('_', "-");
            format!("std::string_view({:?})", s)
        }
        TypeRef::Primitive(Primitive::Uint) => "uint64_t{0}".into(),
        TypeRef::Primitive(Primitive::Int)  => "int64_t{0}".into(),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => "float{0}".into(),
        TypeRef::Primitive(Primitive::Float64 | Primitive::Float)   => "double{0}".into(),
        TypeRef::Named(n) => format!("{}{{}}",to_pascal_case(n)),
        _ => String::new(),
    }).unwrap_or_default();
    if default_init.is_empty() {
        w.line("Variant value{};");
    } else {
        w.line(&format!("Variant value{{{default_init}}};"));
    }
    w.blank();

    // Named constructors for each variant
    for v in &e.variants {
        let vname = to_pascal_case(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null) => {
                w.line(&format!("static {type_name} make_{vname}() {{ return {type_name}{{std::monostate{{}}}}; }}"));
            }
            TypeRef::Primitive(p) => {
                let ct = cpp_primitive(p, opts);
                w.line(&format!("static {type_name} make_{vname}({ct} v) {{ return {type_name}{{v}}; }}"));
            }
            TypeRef::Named(n) => {
                let ct = to_pascal_case(n);
                w.line(&format!("static {type_name} make_{vname}({ct} v) {{ return {type_name}{{v}}; }}"));
            }
            _ => {}
        }
    }
    w.blank();

    w.line(&format!("bool operator==(const {type_name} &o) const noexcept {{ return value == o.value; }}"));
    w.dedent();
    w.line("};");
}

fn emit_array_hpp(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    if let Some(d) = a.doc.as_deref() {
        w.line(&format!("/// {d}"));
    }
    let type_name = to_pascal_case(&a.name);
    let elem_ty   = cpp_typeref(&a.element, opts);
    let cap       = capacity_value(
        a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
        opts.max_array,
    );
    w.line(&format!("struct {type_name} {{"));
    w.indent();
    w.line(&format!("std::array<{elem_ty}, {cap}> items{{}};"));
    w.line("std::size_t count{0};");
    w.blank();
    w.line(&format!("bool operator==(const {type_name} &o) const noexcept {{"));
    w.indent();
    w.line("if (count != o.count) return false;");
    w.line("for (std::size_t i = 0; i < count; i++) {");
    w.indent();
    w.line("if (!(items[i] == o.items[i])) return false;");
    w.dedent();
    w.line("}");
    w.line("return true;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("};");
}

fn emit_alias_hpp(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    if let Some(d) = a.doc.as_deref() {
        w.line(&format!("/// {d}"));
    }
    let type_name = to_pascal_case(&a.name);
    if a.tagged.is_some() || !a.constraints.is_empty() {
        let inner = cpp_typeref(&a.ty, opts);
        w.line(&format!("struct {type_name} {{"));
        w.indent();
        // Generate a valid default for size-constrained string fields so that
        // default-constructed instances satisfy constraints and roundtrip cleanly.
        let size_n = a.constraints.iter().find_map(|c| match c {
            Constraint::SizeExact(n) => Some(*n),
            Constraint::SizeRange { min: Some(n), .. } => Some(*n),
            _ => None,
        });
        let value_default = match (&a.ty, size_n) {
            (TypeRef::Primitive(Primitive::Tstr), Some(n)) => {
                let s = "a".repeat(n);
                format!("value{{std::string_view({:?}, {n})}}", s)
            }
            (TypeRef::Primitive(Primitive::Bstr | Primitive::Any), Some(_n)) => {
                // bstr: leave as-is; static buffer needed, keep empty default
                "value{}".into()
            }
            _ => "value{}".into(),
        };
        w.line(&format!("{inner} {value_default};"));
        w.line(&format!("bool operator==(const {type_name} &o) const noexcept {{ return value == o.value; }}"));
        w.dedent();
        w.line("};");
    } else {
        let inner = cpp_typeref(&a.ty, opts);
        w.line(&format!("using {type_name} = {inner};"));
    }
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let ns    = to_snake_case(name);
    let mut w = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line(&format!("#include \"{name}.hpp\""));
    w.blank();
    w.line(&format!("namespace {ns} {{"));
    w.blank();

    for (_, def) in &module.types {
        w.blank();
        emit_encode_fn(&mut w, def, opts);
        w.blank();
        emit_decode_fn(&mut w, def, opts);
    }

    w.blank();
    w.line(&format!("}} // namespace {ns}"));
    w.finish()
}

fn emit_encode_fn(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(def.name());
    w.line(&format!("int encode(nanocbor_encoder_t *enc, const {type_name} &val) {{"));
    w.indent();

    match def {
        TypeDef::Struct(s) => {
            if let Some(tag) = s.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            let fields: Vec<_> = if opts.dcbor {
                let mut fs: Vec<_> = s.fields.iter().collect();
                fs.sort_by(|a, b| a.name.cmp(&b.name));
                fs
            } else {
                s.fields.iter().collect()
            };
            let req_count = fields.iter()
                .filter(|f| !matches!(f.occurrence, Occurrence::Optional))
                .count();
            let opt_fields: Vec<_> = fields.iter()
                .filter(|f| matches!(f.occurrence, Occurrence::Optional))
                .collect();
            if opt_fields.is_empty() {
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u);"));
            } else {
                let opt_parts: Vec<String> = opt_fields.iter()
                    .map(|f| format!("(val.{}.has_value() ? 1u : 0u)", to_snake_case(&f.name)))
                    .collect();
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u + {});", opt_parts.join(" + ")));
            }
            for f in &fields {
                let fname = to_snake_case(&f.name);
                if matches!(f.occurrence, Occurrence::Optional) {
                    w.line(&format!("if (val.{fname}.has_value()) {{"));
                    w.indent();
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_cpp_encode_field(w, &f.ty, &format!("(*val.{fname})"), &f.occurrence, opts);
                    w.dedent();
                    w.line("}");
                } else {
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_cpp_encode_field(w, &f.ty, &format!("val.{fname}"), &f.occurrence, opts);
                }
            }
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line("return std::visit([enc](auto &&v) -> int {");
            w.indent();
            w.line("using T = std::decay_t<decltype(v)>;");
            for v in &e.variants {
                let _vname = to_pascal_case(&v.name);
                match &v.ty {
                    TypeRef::Primitive(Primitive::Null) => {
                        w.line("if constexpr (std::is_same_v<T, std::monostate>) {");
                        let cddl_str = v.name.to_lowercase().replace('_', "-");
                        w.indent();
                        w.line(&format!("nanocbor_put_tstr(enc, {:?});", cddl_str));
                        w.line("return NANOCBOR_OK;");
                        w.dedent();
                        w.line("}");
                    }
                    TypeRef::Primitive(Primitive::Tstr) => {
                        w.line("if constexpr (std::is_same_v<T, std::string_view>) {");
                        w.indent();
                        w.line("nanocbor_put_tstrn(enc, v.data(), v.size());");
                        w.line("return NANOCBOR_OK;");
                        w.dedent();
                        w.line("}");
                    }
                    TypeRef::Primitive(p) if is_integer_p(p) => {
                        let ct = cpp_primitive(p, opts);
                        w.line(&format!("if constexpr (std::is_same_v<T, {ct}>) {{"));
                        w.indent();
                        w.line("nanocbor_fmt_int(enc, static_cast<int64_t>(v));");
                        w.line("return NANOCBOR_OK;");
                        w.dedent();
                        w.line("}");
                    }
                    TypeRef::Primitive(p) if is_float_p(p) => {
                        let ct = cpp_primitive(p, opts);
                        w.line(&format!("if constexpr (std::is_same_v<T, {ct}>) {{"));
                        w.indent();
                        w.line("nanocbor_fmt_double(enc, static_cast<double>(v));");
                        w.line("return NANOCBOR_OK;");
                        w.dedent();
                        w.line("}");
                    }
                    TypeRef::Named(n) => {
                        let ct = to_pascal_case(n);
                        w.line(&format!("if constexpr (std::is_same_v<T, {ct}>) {{"));
                        w.indent();
                        w.line("return encode(enc, v);");
                        w.dedent();
                        w.line("}");
                    }
                    _ => {}
                }
            }
            w.line("return -1;");
            w.dedent();
            w.line("}, val.value);");
        }
        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line("nanocbor_fmt_array(enc, val.count);");
            w.line("for (std::size_t i = 0; i < val.count; i++) {");
            w.indent();
            emit_cpp_encode_field(w, &a.element, "val.items[i]", &Occurrence::Required, opts);
            w.dedent();
            w.line("}");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            let expr = if a.tagged.is_some() || !a.constraints.is_empty() {
                "val.value"
            } else {
                "val"
            };
            emit_cpp_encode_field(w, &a.ty, expr, &Occurrence::Required, opts);
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_cpp_encode_field(
    w:    &mut IndentWriter,
    ty:   &TypeRef,
    expr: &str,
    _occ: &Occurrence,
    opts: &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = cpp_encode_call(p, expr);
            w.line(&format!("{call};"));
        }
        TypeRef::Named(_) => {
            w.line(&format!("encode(enc, {expr});"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            emit_cpp_encode_field(w, inner, expr, &Occurrence::Required, opts);
        }
        TypeRef::Choice(_) => {
            w.line(&format!("encode(enc, {expr});"));
        }
    }
}

fn cpp_encode_call(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Bool      => format!("nanocbor_fmt_bool(enc, {expr})"),
        Primitive::Null | Primitive::Undefined => "nanocbor_fmt_null(enc)".into(),
        Primitive::Uint      => format!("nanocbor_fmt_uint(enc, {expr})"),
        Primitive::Int       => format!("nanocbor_fmt_int(enc, {expr})"),
        Primitive::Float32 | Primitive::Float16 => format!("nanocbor_fmt_float(enc, {expr})"),
        Primitive::Float64 | Primitive::Float   => format!("nanocbor_fmt_double(enc, {expr})"),
        Primitive::Tstr      => format!("nanocbor_put_tstrn(enc, {expr}.data(), {expr}.size())"),
        Primitive::Bstr | Primitive::Any =>
            format!("nanocbor_put_bstr(enc, reinterpret_cast<const uint8_t*>({expr}.data()), {expr}.size())"),
    }
}

fn emit_decode_fn(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(def.name());
    w.line(&format!(
        "int decode(nanocbor_value_t *dec, {type_name} &out, const Callbacks &cb, void *ctx) {{"
    ));
    w.indent();
    w.line("(void)cb; (void)ctx;");

    match def {
        TypeDef::Struct(s) => {
            if let Some(tag) = s.tagged {
                w.line("{ uint32_t tag;");
                w.line("  if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("  if (tag != {}) return -1; }}", tag.0));
            }
            w.line("nanocbor_value_t map;");
            w.line("if (nanocbor_enter_map(dec, &map) < 0) return -1;");
            w.line("while (!nanocbor_at_end(&map)) {");
            w.indent();
            w.line("const uint8_t *key_ptr; size_t key_len;");
            w.line("if (nanocbor_get_tstr(&map, &key_ptr, &key_len) < 0) return -1;");
            w.line("std::string_view key(reinterpret_cast<const char*>(key_ptr), key_len);");
            for f in &s.fields {
                let fname = to_snake_case(&f.name);
                let fkey  = f.name.as_str();
                w.line(&format!("if (key == {:?}) {{", fkey));
                w.indent();
                emit_cpp_decode_field(w, &f.ty, &format!("out.{fname}"), &f.constraints, fkey, "&map", opts);
                w.dedent();
                w.line("} else");
            }
            w.line("{");
            w.indent();
            w.line("if (cb.on_unknown_field) cb.on_unknown_field(ctx, key);");
            w.line("nanocbor_skip(&map);");
            w.dedent();
            w.line("}");
            w.dedent();
            w.line("}");
            w.line("nanocbor_leave_container(dec, &map);");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line("{ uint32_t tag;");
                w.line("  if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("  if (tag != {}) return -1; }}", tag.0));
            }
            w.line("uint8_t major = nanocbor_get_type(dec);");
            w.line("if (major == NANOCBOR_TYPE_TSTR) {");
            w.indent();
            w.line("const uint8_t *s; size_t slen;");
            w.line("if (nanocbor_get_tstr(dec, &s, &slen) < 0) return -1;");
            w.line("std::string_view sv(reinterpret_cast<const char*>(s), slen);");
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr | Primitive::Null)) {
                    let cddl_str = v.name.to_lowercase().replace('_', "-");
                    let vname = to_pascal_case(&v.name);
                    let type_name2 = to_pascal_case(&e.name);
                    w.line(&format!("if (sv == {:?}) {{ out = {}::make_{}(sv); return NANOCBOR_OK; }}", cddl_str, type_name2, vname));
                }
            }
            w.line("return -1;");
            w.dedent();
            w.line("} else if (major == NANOCBOR_TYPE_UINT || major == NANOCBOR_TYPE_NINT) {");
            w.indent();
            w.line("int64_t n; if (nanocbor_get_int64(dec, &n) < 0) return -1;");
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Int | Primitive::Uint)) {
                    let vname = to_pascal_case(&v.name);
                    let type_name2 = to_pascal_case(&e.name);
                    w.line(&format!("out = {}::make_{}(n); return NANOCBOR_OK;", type_name2, vname));
                    break;
                }
            }
            w.line("return -1;");
            w.dedent();
            w.line("}");
            w.line("return -1;");
        }
        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line("{ uint32_t tag;");
                w.line("  if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("  if (tag != {}) return -1; }}", tag.0));
            }
            let cap = capacity_value(
                a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
                opts.max_array,
            );
            w.line("nanocbor_value_t arr;");
            w.line("if (nanocbor_enter_array(dec, &arr) < 0) return -1;");
            w.line("out.count = 0;");
            w.line(&format!("while (!nanocbor_at_end(&arr) && out.count < {cap}) {{"));
            w.indent();
            emit_cpp_decode_field(w, &a.element, "out.items[out.count]", &[], "item", "&arr", opts);
            w.line("out.count++;");
            w.dedent();
            w.line("}");
            w.line("nanocbor_leave_container(dec, &arr);");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line("{ uint32_t tag;");
                w.line("  if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("  if (tag != {}) return -1; }}", tag.0));
            }
            let dest = if a.tagged.is_some() || !a.constraints.is_empty() {
                "out.value"
            } else {
                "out"
            };
            emit_cpp_decode_field(w, &a.ty, dest, &a.constraints, "value", "dec", opts);
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_cpp_decode_field(
    w:           &mut IndentWriter,
    ty:          &TypeRef,
    dest:        &str,
    constraints: &[Constraint],
    field_name:  &str,
    dec_expr:    &str,
    opts:        &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = cpp_decode_call(p, dest, dec_expr);
            w.line(&format!("if ({call} < 0) return -1;"));
            for c in constraints {
                if let Some(check) = cpp_constraint_check(c, dest, p) {
                    w.line(&format!("if (!({check})) {{"));
                    w.indent();
                    w.line(&format!(
                        "if (cb.on_error) cb.on_error(ctx, {{ErrorCode::ValidationFailed, {:?}}});",
                        field_name
                    ));
                    w.line("return -1;");
                    w.dedent();
                    w.line("}");
                }
            }
        }
        TypeRef::Named(_) => {
            w.line(&format!("if (decode({dec_expr}, {dest}, cb, ctx) < 0) return -1;"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line("{ uint32_t tag;");
            w.line(&format!("  if (nanocbor_get_tag({dec_expr}, &tag) < 0) return -1;"));
            w.line(&format!("  if (tag != {}) return -1;", tag.0));
            emit_cpp_decode_field(w, inner, dest, constraints, field_name, dec_expr, opts);
            w.line("}");
        }
        TypeRef::Choice(_) => {
            w.line(&format!("nanocbor_skip({dec_expr}); // choice"));
        }
    }
}

/// Type-aware constraint check: for integer primitives `.size N` means
/// "fits in N bytes" (value-range), not a `.size()` call.
fn cpp_constraint_check(c: &Constraint, val_expr: &str, p: &Primitive) -> Option<String> {
    match c {
        Constraint::SizeExact(n) => match p {
            Primitive::Uint => {
                let max = cpp_uint_max_for_bytes(*n)?;
                Some(format!("{val_expr} <= {max}"))
            }
            Primitive::Int => {
                let (lo, hi) = cpp_int_range_for_bytes(*n)?;
                Some(format!("{val_expr} >= {lo} && {val_expr} <= {hi}"))
            }
            _ => constraint_to_cpp_check(c, val_expr),
        },
        Constraint::SizeRange { .. } => match p {
            Primitive::Uint | Primitive::Int => None, // uncommon; skip
            _ => constraint_to_cpp_check(c, val_expr),
        },
        _ => constraint_to_cpp_check(c, val_expr),
    }
}

fn cpp_uint_max_for_bytes(n: usize) -> Option<String> {
    match n {
        1 => Some("0xFFULL".into()),
        2 => Some("0xFFFFULL".into()),
        4 => Some("0xFFFFFFFFULL".into()),
        8 => None, // uint64 always fits
        _ => None,
    }
}

fn cpp_int_range_for_bytes(n: usize) -> Option<(i64, i64)> {
    match n {
        1 => Some((-128, 127)),
        2 => Some((-32768, 32767)),
        4 => Some((-2147483648, 2147483647)),
        8 => None,
        _ => None,
    }
}

fn cpp_decode_call(p: &Primitive, dest: &str, dec: &str) -> String {
    match p {
        Primitive::Bool      => format!("nanocbor_get_bool({dec}, &{dest})"),
        Primitive::Null | Primitive::Undefined => format!("nanocbor_get_null({dec})"),
        Primitive::Uint      => format!("nanocbor_get_uint64({dec}, reinterpret_cast<uint64_t*>(&{dest}))"),
        Primitive::Int       => format!("nanocbor_get_int64({dec}, reinterpret_cast<int64_t*>(&{dest}))"),
        Primitive::Float32 | Primitive::Float16 =>
            format!("nanocbor_get_float({dec}, &{dest})"),
        Primitive::Float64 | Primitive::Float =>
            format!("nanocbor_get_double({dec}, &{dest})"),
        Primitive::Tstr => format!(
            "({{ const uint8_t *_p; size_t _l; int _r = nanocbor_get_tstr({dec}, &_p, &_l); \
             if (_r >= 0) {dest} = std::string_view(reinterpret_cast<const char*>(_p), _l); _r; }})"
        ),
        Primitive::Bstr | Primitive::Any => format!(
            "({{ const uint8_t *_p; size_t _l; int _r = nanocbor_get_bstr({dec}, &_p, &_l); \
             if (_r >= 0) {dest} = std::string_view(reinterpret_cast<const char*>(_p), _l); _r; }})"
        ),
    }
}

// ── Test file ─────────────────────────────────────────────────────────────────

/// Returns the first concrete Primitive in a TypeRef, following Tagged and Choice.
fn effective_primitive(ty: &TypeRef) -> Option<&Primitive> {
    match ty {
        TypeRef::Primitive(p)     => Some(p),
        TypeRef::Choice(cs)       => cs.first().and_then(|c| effective_primitive(c)),
        TypeRef::Tagged(_, inner) => effective_primitive(inner),
        _ => None,
    }
}

/// If `type_name` resolves to a `tstr .size N` alias, return `Some(N)`.
fn tstr_size_constraint_for(type_name: &str, module: &IrModule) -> Option<usize> {
    match module.types.get(type_name)? {
        TypeDef::Alias(a) if matches!(&a.ty, TypeRef::Primitive(Primitive::Tstr)) => {
            a.constraints.iter().find_map(|c| match c {
                Constraint::SizeExact(n) => Some(*n),
                Constraint::SizeRange { min: Some(n), .. } => Some(*n),
                _ => None,
            })
        }
        _ => None,
    }
}

fn emit_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let ns    = to_snake_case(name);
    let mut w = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line("// Roundtrip encode/decode tests");
    w.line(&format!("#include \"{name}.hpp\""));
    w.line("#include <cassert>");
    w.line("#include <cstdio>");
    w.blank();

    w.line(&format!("using namespace {ns};"));
    w.blank();
    w.line("static uint8_t buf[1024];");
    w.blank();

    for (_, def) in &module.types {
        emit_cpp_type_test(&mut w, def, module, opts);
        w.blank();
    }

    w.line("int main() {");
    w.indent();
    for (_, def) in &module.types {
        let fn_name = to_snake_case(def.name());
        w.line(&format!("test_{fn_name}_roundtrip();"));
    }
    w.line("std::printf(\"All C++ roundtrip tests passed.\\n\");");
    w.line("return 0;");
    w.dedent();
    w.line("}");

    w.finish()
}

fn emit_cpp_type_test(w: &mut IndentWriter, def: &TypeDef, module: &IrModule, _opts: &CodegenOptions) {
    let type_name = to_pascal_case(def.name());
    let fn_name   = to_snake_case(def.name());

    w.line(&format!("static void test_{fn_name}_roundtrip() {{"));
    w.indent();

    match def {
        TypeDef::Alias(a) if !a.constraints.is_empty() => {
            // For size-constrained aliases, construct a valid test value.
            let n = a.constraints.iter().find_map(|c| match c {
                cddlc_ir::Constraint::SizeExact(n) => Some(*n),
                cddlc_ir::Constraint::SizeRange { min: Some(n), .. } => Some(*n),
                _ => None,
            });
            if let Some(n) = n {
                match &a.ty {
                    TypeRef::Primitive(Primitive::Tstr) => {
                        let s = "a".repeat(n);
                        w.line(&format!("{type_name} original{{ std::string_view({:?}, {n}) }};", s));
                    }
                    TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => {
                        // bstr alias: value is std::string_view over a static byte array
                        let bytes: Vec<String> = (0..n).map(|i| format!("0x{:02x}", (i % 256) as u8)).collect();
                        w.line(&format!("static const uint8_t _bytes[{n}] = {{{}}};", bytes.join(", ")));
                        w.line(&format!("{type_name} original{{ std::string_view(reinterpret_cast<const char*>(_bytes), {n}) }};"));
                    }
                    _ => { w.line(&format!("{type_name} original{{}};")) }
                }
            } else {
                w.line(&format!("{type_name} original{{}};"));
            }
        }
        TypeDef::Enum(e) => {
            if let Some(v) = e.variants.first() {
                let vname = to_pascal_case(&v.name);
                let arg = match &v.ty {
                    TypeRef::Primitive(Primitive::Null) => String::new(),
                    TypeRef::Primitive(Primitive::Tstr) => {
                        let cddl_str = v.name.to_lowercase().replace('_', "-");
                        format!("std::string_view({:?})", cddl_str)
                    }
                    TypeRef::Primitive(Primitive::Uint) => "0u".into(),
                    TypeRef::Primitive(Primitive::Int)  => "0".into(),
                    TypeRef::Primitive(p) => cpp_primitive(p, _opts).to_string() + "{}",
                    TypeRef::Named(n) => format!("{}{{}}",to_pascal_case(n)),
                    _ => String::new(),
                };
                w.line(&format!("{type_name} original = {type_name}::make_{vname}({arg});"));
            } else {
                w.line(&format!("{type_name} original{{}};"));
            }
        }
        TypeDef::Struct(s) => {
            w.line(&format!("{type_name} original{{}};"));
            for f in &s.fields {
                let fname = to_snake_case(&f.name);
                // Skip optional and repeated fields
                if !matches!(f.occurrence, Occurrence::Required) {
                    continue;
                }
                // Resolve tagged inner type
                let effective_ty = match &f.ty {
                    TypeRef::Tagged(_, inner) => inner.as_ref(),
                    other => other,
                };
                match effective_ty {
                    TypeRef::Primitive(Primitive::Uint) => {
                        w.line(&format!("original.{fname} = 42u;"));
                    }
                    TypeRef::Primitive(Primitive::Int) => {
                        w.line(&format!("original.{fname} = -1;"));
                    }
                    TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => {
                        w.line(&format!("original.{fname} = 1.0f;"));
                    }
                    TypeRef::Primitive(Primitive::Float64 | Primitive::Float) => {
                        w.line(&format!("original.{fname} = 1.0;"));
                    }
                    TypeRef::Primitive(Primitive::Bool) => {
                        w.line(&format!("original.{fname} = true;"));
                    }
                    TypeRef::Primitive(Primitive::Tstr) => {
                        w.line(&format!("static const char _{fname}_str[] = \"hello\";"));
                        w.line(&format!("original.{fname} = std::string_view(_{fname}_str);"));
                    }
                    TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => {
                        w.line(&format!("static const uint8_t _{fname}_cbor[1] = {{0xf6}};"));
                        w.line(&format!("original.{fname} = std::string_view(reinterpret_cast<const char*>(_{fname}_cbor), 1);"));
                    }
                    TypeRef::Choice(_) => {
                        match effective_primitive(effective_ty) {
                            Some(Primitive::Tstr) => {
                                w.line(&format!("static const char _{fname}_str[] = \"hello\";"));
                                w.line(&format!("original.{fname} = std::string_view(_{fname}_str);"));
                            }
                            Some(Primitive::Bstr | Primitive::Any) => {
                                w.line(&format!("static const uint8_t _{fname}_cbor[1] = {{0xf6}};"));
                                w.line(&format!("original.{fname} = std::string_view(reinterpret_cast<const char*>(_{fname}_cbor), 1);"));
                            }
                            _ => {}
                        }
                    }
                    TypeRef::Named(n) => {
                        if let Some(sz) = tstr_size_constraint_for(n, module) {
                            let s = "a".repeat(sz);
                            w.line(&format!("{{ static const char _{fname}_str[] = {s:?}; original.{fname} = {}{{ std::string_view(_{fname}_str, {sz}) }}; }}", to_pascal_case(n)));
                        }
                        // Otherwise leave as default {}
                    }
                    _ => {
                        // Leave as default {}
                    }
                }
            }
        }
        _ => {
            w.line(&format!("{type_name} original{{}};"));
        }
    }

    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line("assert(encode(&enc, original) == 0);");
    w.line("std::size_t enc_len = nanocbor_encoded_len(&enc);");
    w.blank();
    w.line(&format!("{type_name} decoded{{}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line("assert(decode(&dec, decoded) == 0);");
    w.line("assert(original == decoded);");
    w.line(&format!("std::printf(\"{fn_name}_roundtrip: PASS\\n\");"));

    w.dedent();
    w.line("}");
}

// ── C++ type helpers ──────────────────────────────────────────────────────────

fn cpp_field_type(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = cpp_typeref(ty, opts);
    match occ {
        Occurrence::Optional => format!("std::optional<{base}>"),
        Occurrence::ZeroOrMore { capacity } | Occurrence::OneOrMore { capacity }
        | Occurrence::Bounded { capacity, .. } => {
            let cap = capacity_value(capacity, opts.max_array);
            format!("std::array<{base}, {cap}>")
        }
        Occurrence::Required => base,
    }
}

fn cpp_typeref(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)     => cpp_primitive(p, opts).to_owned(),
        TypeRef::Named(n)         => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => cpp_typeref(inner, opts),
        TypeRef::Choice(cs)       => cs.first()
            .map(|c| cpp_typeref(c, opts))
            .unwrap_or_else(|| "std::monostate".into()),
    }
}

fn cpp_primitive<'a>(p: &Primitive, _opts: &CodegenOptions) -> &'a str {
    match p {
        Primitive::Bool      => "bool",
        Primitive::Null | Primitive::Undefined => "std::monostate",
        Primitive::Uint      => "uint64_t",
        Primitive::Int       => "int64_t",
        Primitive::Float16 | Primitive::Float32 => "float",
        Primitive::Float64 | Primitive::Float   => "double",
        Primitive::Tstr      => "std::string_view",
        Primitive::Bstr | Primitive::Any        => "std::string_view",
    }
}

fn is_integer_p(p: &Primitive) -> bool {
    matches!(p, Primitive::Uint | Primitive::Int)
}

fn is_float_p(p: &Primitive) -> bool {
    matches!(p, Primitive::Float | Primitive::Float16 | Primitive::Float32 | Primitive::Float64)
}

// ── C++ JSON backend (nlohmann/json) ─────────────────────────────────────────

fn emit_cmake_json_cpp(name: &str, _opts: &CodegenOptions) -> String {
    format!(r#"# @generated by cddlc — do not edit manually
cmake_minimum_required(VERSION 3.16)
project({name}_json CXX)

set(CMAKE_CXX_STANDARD 17)

include(FetchContent)
FetchContent_Declare(nlohmann_json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        master
)
set(JSON_BuildTests OFF CACHE INTERNAL "")
FetchContent_MakeAvailable(nlohmann_json)

add_library({name}_json
    src/{name}.cpp
)
target_include_directories({name}_json PUBLIC include)
target_link_libraries({name}_json PUBLIC nlohmann_json::nlohmann_json)

enable_testing()
add_executable(test_roundtrip test/test_roundtrip.cpp)
target_link_libraries(test_roundtrip PRIVATE {name}_json)
add_test(NAME roundtrip COMMAND test_roundtrip)
"#)
}

fn emit_header_json_cpp(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let guard = name.to_uppercase().replace('-', "_");
    let ns    = name.replace('-', "_");
    let mut w = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line("// Format: JSON (RFC 8259)");
    w.line(&format!("#ifndef {guard}_JSON_HPP"));
    w.line(&format!("#define {guard}_JSON_HPP"));
    w.blank();
    w.line("#include <cstdint>");
    w.line("#include <string>");
    w.line("#include <vector>");
    w.line("#include <optional>");
    w.line("#include <variant>");
    w.line("#include <stdexcept>");
    w.line("#include <nlohmann/json.hpp>");
    w.blank();
    w.line(&format!("namespace {ns} {{"));
    w.blank();

    // Base64url helpers
    w.line("std::string b64url_encode(const std::vector<uint8_t>& data);");
    w.line("std::vector<uint8_t> b64url_decode(const std::string& s);");
    w.blank();

    // Emit type declarations
    for (_, def) in &module.types {
        emit_cpp_json_type_decl(&mut w, def, opts);
        w.blank();
    }

    w.line(&format!("}} // namespace {ns}"));
    w.blank();
    w.line(&format!("#endif // {guard}_JSON_HPP"));
    w.finish()
}

fn cpp_json_field_type(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool => "bool".into(),
            Primitive::Uint => "uint64_t".into(),
            Primitive::Int  => "int64_t".into(),
            Primitive::Float32 | Primitive::Float16 => "float".into(),
            Primitive::Float64 | Primitive::Float => "double".into(),
            Primitive::Tstr => "std::string".into(),
            Primitive::Bstr | Primitive::Any => "std::vector<uint8_t>".into(),
            Primitive::Null | Primitive::Undefined => "std::monostate".into(),
        },
        TypeRef::Named(n) => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => cpp_json_field_type(inner, opts),
        TypeRef::Choice(_) => "nlohmann::json".into(),
    }
}

fn cpp_json_field_type_with_occ(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = cpp_json_field_type(ty, opts);
    match occ {
        Occurrence::Optional => format!("std::optional<{base}>"),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => format!("std::vector<{base}>"),
        Occurrence::Required => base,
    }
}

fn emit_cpp_json_type_decl(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => {
            let ctype = to_pascal_case(&s.name);
            w.line(&format!("struct {ctype} {{"));
            w.indent();
            for f in &s.fields {
                let fname = to_snake_case(&f.name);
                let ty    = cpp_json_field_type_with_occ(&f.ty, &f.occurrence, opts);
                w.line(&format!("{ty} {fname}{{}};"));
            }
            w.blank();
            w.line("std::vector<uint8_t> encode() const;");
            w.line(&format!("static {ctype} decode(const std::vector<uint8_t>& data);"));
            w.dedent();
            w.line("};");
        }
        TypeDef::Enum(e) => {
            let ctype = to_pascal_case(&e.name);
            // Emit as std::variant for mixed enums or string enum
            let all_str = e.variants.iter().all(|v|
                matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));
            if all_str {
                let variants: Vec<String> = e.variants.iter()
                    .map(|v| format!("{:?}", v.name.to_lowercase().replace('_', "-")))
                    .collect();
                w.line(&format!("// {ctype}: string enum ({} variants)", variants.len()));
                w.line(&format!("using {ctype} = std::string;"));
            } else {
                // Emit as tagged union via JSON
                w.line(&format!("struct {ctype} {{"));
                w.indent();
                w.line("nlohmann::json value;");
                w.blank();
                w.line("std::vector<uint8_t> encode() const;");
                w.line(&format!("static {ctype} decode(const std::vector<uint8_t>& data);"));
                w.dedent();
                w.line("};");
            }
        }
        TypeDef::Array(a) => {
            let ctype    = to_pascal_case(&a.name);
            let elem_ty  = cpp_json_field_type(&a.element, opts);
            w.line(&format!("using {ctype} = std::vector<{elem_ty}>;"));
            w.line(&format!("std::vector<uint8_t> encode_{ctype}(const {ctype}& val);"));
            w.line(&format!("{ctype} decode_{ctype}(const std::vector<uint8_t>& data);"));
        }
        TypeDef::Alias(a) => {
            let ctype    = to_pascal_case(&a.name);
            let inner_ty = cpp_json_field_type(&a.ty, opts);
            w.line(&format!("struct {ctype} {{"));
            w.indent();
            w.line(&format!("{inner_ty} value{{}};"));
            w.blank();
            w.line("std::vector<uint8_t> encode() const;");
            w.line(&format!("static {ctype} decode(const std::vector<uint8_t>& data);"));
            w.dedent();
            w.line("};");
        }
        TypeDef::Map(_) => {}
    }
}

fn emit_source_json_cpp(module: &IrModule, opts: &CodegenOptions) -> String {
    let name = module.name.as_str();
    let ns   = name.replace('-', "_");
    let mut w = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line(&format!("#include \"{name}.hpp\""));
    w.line("#include <cstring>");
    w.blank();
    w.line(&format!("namespace {ns} {{"));
    w.blank();

    // Base64url impl
    w.line("static const char B64URL[] =");
    w.line("    \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_\";");
    w.blank();
    w.line("std::string b64url_encode(const std::vector<uint8_t>& data) {");
    w.indent();
    w.line("std::string out;");
    w.line("size_t i = 0, n = data.size();");
    w.line("while (i + 2 < n) {");
    w.indent();
    w.line("out += B64URL[(data[i] >> 2) & 0x3F];");
    w.line("out += B64URL[((data[i] << 4) | (data[i+1] >> 4)) & 0x3F];");
    w.line("out += B64URL[((data[i+1] << 2) | (data[i+2] >> 6)) & 0x3F];");
    w.line("out += B64URL[data[i+2] & 0x3F];");
    w.line("i += 3;");
    w.dedent();
    w.line("}");
    w.line("if (i < n) {");
    w.indent();
    w.line("out += B64URL[(data[i] >> 2) & 0x3F];");
    w.line("if (i+1 < n) { out += B64URL[((data[i]<<4)|(data[i+1]>>4))&0x3F]; out += B64URL[(data[i+1]<<2)&0x3F]; }");
    w.line("else { out += B64URL[(data[i] << 4) & 0x3F]; }");
    w.dedent();
    w.line("}");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("std::vector<uint8_t> b64url_decode(const std::string& s) {");
    w.indent();
    w.line("static const int8_t DEC[256] = {");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,");
    w.line("    52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,");
    w.line("    -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,");
    w.line("    15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,63,");
    w.line("    -1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,");
    w.line("    41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1");
    w.line("};");
    w.line("std::vector<uint8_t> out;");
    w.line("size_t i = 0, n = s.size();");
    w.line("while (i + 3 < n) {");
    w.indent();
    w.line("int a=DEC[(uint8_t)s[i]],b=DEC[(uint8_t)s[i+1]],c=DEC[(uint8_t)s[i+2]],d=DEC[(uint8_t)s[i+3]];");
    w.line("if(a<0||b<0||c<0||d<0) break;");
    w.line("out.push_back((a<<2)|(b>>4)); out.push_back((b<<4)|(c>>2)); out.push_back((c<<6)|d);");
    w.line("i += 4;");
    w.dedent();
    w.line("}");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blank();

    for (_, def) in &module.types {
        emit_cpp_json_impl(&mut w, def, opts);
        w.blank();
    }

    w.line(&format!("}} // namespace {ns}"));
    w.finish()
}

fn cpp_json_to_val(ty: &TypeRef, expr: &str) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) =>
            format!("b64url_encode({expr})"),
        TypeRef::Named(_) => format!("nlohmann::json::parse({expr}.encode())"),
        TypeRef::Tagged(_, inner) => cpp_json_to_val(inner, expr),
        _ => expr.to_owned(),
    }
}

fn cpp_json_from_val(ty: &TypeRef, expr: &str, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Uint) => format!("{expr}.get<uint64_t>()"),
        TypeRef::Primitive(Primitive::Int)  => format!("{expr}.get<int64_t>()"),
        TypeRef::Primitive(Primitive::Bool) => format!("{expr}.get<bool>()"),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => format!("{expr}.get<float>()"),
        TypeRef::Primitive(Primitive::Float64 | Primitive::Float) => format!("{expr}.get<double>()"),
        TypeRef::Primitive(Primitive::Tstr) => format!("{expr}.get<std::string>()"),
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) =>
            format!("b64url_decode({expr}.get<std::string>())"),
        TypeRef::Primitive(Primitive::Null | Primitive::Undefined) => "std::monostate{}".into(),
        TypeRef::Named(n) => {
            let ctype = to_pascal_case(n);
            let bytes = format!("std::vector<uint8_t>({expr}.dump().begin(), {expr}.dump().end())");
            format!("{ctype}::decode({bytes})")
        }
        TypeRef::Tagged(_, inner) => cpp_json_from_val(inner, expr, opts),
        TypeRef::Choice(_) => expr.to_owned(),
    }
}

fn emit_cpp_json_impl(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => {
            let ctype = to_pascal_case(&s.name);
            w.line(&format!("std::vector<uint8_t> {ctype}::encode() const {{"));
            w.indent();
            w.line("nlohmann::json j = nlohmann::json::object();");
            for f in &s.fields {
                let fname = to_snake_case(&f.name);
                let key   = f.name.as_str();
                let _val  = cpp_json_to_val(&f.ty, &fname);
                match &f.occurrence {
                    Occurrence::Optional => {
                        w.line(&format!("if ({fname}.has_value()) j[{key:?}] = {val};", fname=format!("this->{fname}"), val=cpp_json_to_val(&f.ty, &format!("this->{fname}.value()"))));
                    }
                    _ => {
                        w.line(&format!("j[{key:?}] = {};", cpp_json_to_val(&f.ty, &format!("this->{fname}"))));
                    }
                }
            }
            w.line("auto s = j.dump();");
            w.line("return std::vector<uint8_t>(s.begin(), s.end());");
            w.dedent();
            w.line("}");
            w.blank();

            w.line(&format!("{ctype} {ctype}::decode(const std::vector<uint8_t>& data) {{"));
            w.indent();
            w.line("auto j = nlohmann::json::parse(data.begin(), data.end());");
            w.line(&format!("{ctype} out{{}};"));
            for f in &s.fields {
                let fname = to_snake_case(&f.name);
                let key   = f.name.as_str();
                match &f.occurrence {
                    Occurrence::Optional => {
                        w.line(&format!("if (j.contains({key:?})) out.{fname} = {};", cpp_json_from_val(&f.ty, &format!("j[{key:?}]"), opts)));
                    }
                    _ => {
                        w.line(&format!("out.{fname} = {};", cpp_json_from_val(&f.ty, &format!("j.at({key:?})"), opts)));
                    }
                }
            }
            w.line("return out;");
            w.dedent();
            w.line("}");
        }
        TypeDef::Enum(e) => {
            let ctype   = to_pascal_case(&e.name);
            let all_str = e.variants.iter().all(|v|
                matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));

            if all_str {
                // string enum — type alias, no methods needed
            } else {
                w.line(&format!("std::vector<uint8_t> {ctype}::encode() const {{"));
                w.indent();
                w.line("auto s = value.dump();");
                w.line("return std::vector<uint8_t>(s.begin(), s.end());");
                w.dedent();
                w.line("}");
                w.blank();

                w.line(&format!("{ctype} {ctype}::decode(const std::vector<uint8_t>& data) {{"));
                w.indent();
                w.line(&format!("{ctype} out{{}};"));
                w.line("out.value = nlohmann::json::parse(data.begin(), data.end());");
                w.line("return out;");
                w.dedent();
                w.line("}");
            }
        }
        TypeDef::Array(a) => {
            let ctype   = to_pascal_case(&a.name);
            let elem_ty = cpp_json_field_type(&a.element, opts);
            w.line(&format!("std::vector<uint8_t> encode_{ctype}(const {ctype}& val) {{"));
            w.indent();
            if matches!(&a.element, TypeRef::Primitive(Primitive::Bstr | Primitive::Any)) {
                w.line("nlohmann::json arr = nlohmann::json::array();");
                w.line("for (const auto& item : val) arr.push_back(b64url_encode(item));");
                w.line("auto s = arr.dump();");
            } else {
                w.line("nlohmann::json arr = val;");
                w.line("auto s = arr.dump();");
            }
            w.line("return std::vector<uint8_t>(s.begin(), s.end());");
            w.dedent();
            w.line("}");
            w.blank();

            w.line(&format!("{ctype} decode_{ctype}(const std::vector<uint8_t>& data) {{"));
            w.indent();
            w.line("auto j = nlohmann::json::parse(data.begin(), data.end());");
            if matches!(&a.element, TypeRef::Primitive(Primitive::Bstr | Primitive::Any)) {
                w.line(&format!("{ctype} out;"));
                w.line("for (const auto& item : j) out.push_back(b64url_decode(item.get<std::string>()));");
                w.line("return out;");
            } else {
                w.line(&format!("return j.get<{ctype}>();"));
            }
            w.dedent();
            w.line("}");

            let _ = elem_ty;
        }
        TypeDef::Alias(a) => {
            let ctype    = to_pascal_case(&a.name);
            w.line(&format!("std::vector<uint8_t> {ctype}::encode() const {{"));
            w.indent();
            let val = cpp_json_to_val(&a.ty, "this->value");
            w.line(&format!("nlohmann::json j = {val};"));
            w.line("auto s = j.dump();");
            w.line("return std::vector<uint8_t>(s.begin(), s.end());");
            w.dedent();
            w.line("}");
            w.blank();

            w.line(&format!("{ctype} {ctype}::decode(const std::vector<uint8_t>& data) {{"));
            w.indent();
            w.line("auto j = nlohmann::json::parse(data.begin(), data.end());");
            w.line(&format!("{ctype} out{{}};"));
            w.line(&format!("out.value = {};", cpp_json_from_val(&a.ty, "j", opts)));
            w.line("return out;");
            w.dedent();
            w.line("}");
        }
        TypeDef::Map(_) => {}
    }
}

fn emit_tests_json_cpp(module: &IrModule, opts: &CodegenOptions) -> String {
    let name = module.name.as_str();
    let ns   = name.replace('-', "_");
    let mut w = IndentWriter::new(4);

    w.line("// @generated by cddlc — do not edit manually");
    w.line(&format!("#include \"{name}.hpp\""));
    w.line("#include <cassert>");
    w.line("#include <cstdio>");
    w.blank();
    w.line(&format!("using namespace {ns};"));
    w.blank();

    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(s) => {
                let ctype = to_pascal_case(&s.name);
                w.line(&format!("void test_{ctype}() {{"));
                w.indent();
                w.line(&format!("{ctype} original{{}};"));
                w.line("auto encoded = original.encode();");
                w.line(&format!("auto decoded = {ctype}::decode(encoded);"));
                w.line("(void)decoded;");
                w.dedent();
                w.line("}");
                w.blank();
            }
            TypeDef::Enum(e) => {
                let ctype   = to_pascal_case(&e.name);
                let all_str = e.variants.iter().all(|v|
                    matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));
                if !all_str {
                    w.line(&format!("void test_{ctype}() {{"));
                    w.indent();
                    w.line(&format!("{ctype} original{{}};"));
                    w.line("auto encoded = original.encode();");
                    w.line(&format!("auto decoded = {ctype}::decode(encoded);"));
                    w.line("(void)decoded;");
                    w.dedent();
                    w.line("}");
                    w.blank();
                }
            }
            TypeDef::Array(a) => {
                let ctype = to_pascal_case(&a.name);
                w.line(&format!("void test_{ctype}() {{"));
                w.indent();
                w.line(&format!("{ctype} original{{}};"));
                w.line(&format!("auto encoded = encode_{ctype}(original);"));
                w.line(&format!("auto decoded = decode_{ctype}(encoded);"));
                w.line("(void)decoded;");
                w.dedent();
                w.line("}");
                w.blank();
            }
            TypeDef::Alias(a) => {
                let ctype = to_pascal_case(&a.name);
                w.line(&format!("void test_{ctype}() {{"));
                w.indent();
                w.line(&format!("{ctype} original{{}};"));
                w.line("auto encoded = original.encode();");
                w.line(&format!("auto decoded = {ctype}::decode(encoded);"));
                w.line("(void)decoded;");
                w.dedent();
                w.line("}");
                w.blank();
            }
            TypeDef::Map(_) => {}
        }
        let _ = opts;
    }

    w.line("int main() {");
    w.indent();
    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(s) => { let ctype = to_pascal_case(&s.name); w.line(&format!("test_{ctype}();")); }
            TypeDef::Enum(e) => {
                let ctype   = to_pascal_case(&e.name);
                let all_str = e.variants.iter().all(|v|
                    matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));
                if !all_str { w.line(&format!("test_{ctype}();")); }
            }
            TypeDef::Array(a) => { let ctype = to_pascal_case(&a.name); w.line(&format!("test_{ctype}();")); }
            TypeDef::Alias(a) => { let ctype = to_pascal_case(&a.name); w.line(&format!("test_{ctype}();")); }
            TypeDef::Map(_) => {}
        }
    }
    w.line("std::printf(\"All C++ JSON roundtrip tests passed.\\n\");");
    w.line("return 0;");
    w.dedent();
    w.line("}");

    w.finish()
}
